export const pmndrsCommonPrimitiveSourceRefs = [
  "projects/repos/examples/demos/scrollcontrols-with-minimap/src/App.jsx",
  "projects/repos/examples/demos/useintersect-and-scrollcontrols/src/App.jsx",
  "projects/repos/examples/demos/tying-canvas-to-scroll-offset/src/App.jsx",
  "projects/repos/examples/demos/html-annotations/src/App.jsx",
  "projects/repos/examples/demos/html-markers/src/App.jsx",
  "projects/repos/examples/demos/mixing-html-and-webgl/src/App.jsx",
  "projects/repos/examples/demos/instances/src/App.jsx",
  "projects/repos/examples/demos/instanced-vertex-colors/src/App.jsx",
  "projects/repos/examples/demos/floating-instanced-shoes/src/App.jsx",
  "projects/repos/examples/demos/bounds-and-makedefault/src/App.jsx",
  "projects/repos/examples/demos/stage-presets-gltfjsx/src/App.jsx",
  "projects/repos/examples/demos/camera-shake/src/App.jsx",
  "projects/repos/drei/src/core/Gltf.tsx",
  "projects/repos/drei/src/core/Texture.tsx",
  "projects/repos/drei/src/core/PerspectiveCamera.tsx",
  "projects/repos/drei/src/core/OrthographicCamera.tsx",
  "projects/repos/drei/src/core/Bounds.tsx",
  "projects/repos/drei/src/core/Center.tsx",
  "projects/repos/drei/src/core/Instances.tsx",
  "projects/repos/drei/src/core/Float.tsx",
  "projects/repos/drei/src/core/CameraShake.tsx",
  "projects/repos/drei/src/core/shaderMaterial.tsx",
  "projects/repos/drei/src/web/Html.tsx",
  "projects/repos/drei/src/web/ScrollControls.tsx",
] as const

export const pmndrsCommonPrimitiveCounts = [
  {
    primitive: "useGLTF",
    importSource: "@react-three/drei",
    sourceFiles: 98,
    demos: 88,
    threeEffectModule: "assetPrimitives",
  },
  {
    primitive: "Environment",
    importSource: "@react-three/drei",
    sourceFiles: 71,
    demos: 70,
    threeEffectModule: "assetPrimitives plus scene-specific lighting",
  },
  {
    primitive: "OrbitControls",
    importSource: "@react-three/drei",
    sourceFiles: 61,
    demos: 61,
    threeEffectModule: "scene-specific controls, not pulled into core yet",
  },
  {
    primitive: "useTexture",
    importSource: "@react-three/drei",
    sourceFiles: 25,
    demos: 23,
    threeEffectModule: "assetPrimitives",
  },
  {
    primitive: "ScrollControls/useScroll",
    importSource: "@react-three/drei",
    sourceFiles: 17,
    demos: 18,
    threeEffectModule: "scrollPrimitives",
  },
  {
    primitive: "Text",
    importSource: "@react-three/drei",
    sourceFiles: 19,
    demos: 18,
    threeEffectModule: "scene-specific font/text meshes, not pulled into core yet",
  },
  {
    primitive: "Float",
    importSource: "@react-three/drei",
    sourceFiles: 17,
    demos: 16,
    threeEffectModule: "motionPrimitives",
  },
  {
    primitive: "PerspectiveCamera/OrthographicCamera",
    importSource: "@react-three/drei",
    sourceFiles: 21,
    demos: 23,
    threeEffectModule: "cameraPrimitives",
  },
  {
    primitive: "Html",
    importSource: "@react-three/drei",
    sourceFiles: 13,
    demos: 13,
    threeEffectModule: "htmlOverlayPrimitives",
  },
  {
    primitive: "Bounds/Center",
    importSource: "@react-three/drei",
    sourceFiles: 19,
    demos: 19,
    threeEffectModule: "cameraPrimitives",
  },
  {
    primitive: "Instances/Instance",
    importSource: "@react-three/drei",
    sourceFiles: 6,
    demos: 6,
    threeEffectModule: "instancePrimitives",
  },
  {
    primitive: "CameraShake",
    importSource: "@react-three/drei",
    sourceFiles: 5,
    demos: 5,
    threeEffectModule: "motionPrimitives",
  },
  {
    primitive: "shaderMaterial",
    importSource: "@react-three/drei",
    sourceFiles: 9,
    demos: 9,
    threeEffectModule: "shaderMaterialPrimitives",
  },
] as const
