export const pmndrsCommonPrimitiveSourceRefs = [
  "projects/repos/examples/demos/scrollcontrols-with-minimap/src/App.jsx",
  "projects/repos/examples/demos/useintersect-and-scrollcontrols/src/App.jsx",
  "projects/repos/examples/demos/tying-canvas-to-scroll-offset/src/App.jsx",
  "projects/repos/examples/demos/html-annotations/src/App.jsx",
  "projects/repos/examples/demos/html-markers/src/App.jsx",
  "projects/repos/examples/demos/mixing-html-and-webgl/src/App.jsx",
  "projects/repos/examples/demos/instances/src/App.jsx",
  "projects/repos/examples/demos/instanced-vertex-colors/src/App.jsx",
  "projects/repos/examples/demos/floating-instanced-shoes/src/App.jsx",
  "projects/repos/examples/demos/bounds-and-makedefault/src/App.jsx",
  "projects/repos/examples/demos/stage-presets-gltfjsx/src/App.jsx",
  "projects/repos/examples/demos/camera-shake/src/App.jsx",
  "projects/repos/examples/demos/aquarium/src/App.jsx",
  "projects/repos/examples/demos/baking-soft-shadows/src/App.jsx",
  "projects/repos/examples/demos/basic-demo/src/App.jsx",
  "projects/repos/examples/demos/building-dynamic-envmaps/src/App.jsx",
  "projects/repos/examples/demos/cards/src/App.jsx",
  "projects/repos/examples/demos/cell-fracture/src/App.jsx",
  "projects/repos/examples/demos/clouds/src/App.jsx",
  "projects/repos/examples/demos/gltf-animations/src/App.jsx",
  "projects/repos/examples/demos/image-gallery/src/App.jsx",
  "projects/repos/examples/demos/inverted-stencil-buffer/src/App.jsx",
  "projects/repos/examples/demos/portal-shapes/src/App.jsx",
  "projects/repos/drei/src/core/Gltf.tsx",
  "projects/repos/drei/src/core/Texture.tsx",
  "projects/repos/drei/src/core/Environment.tsx",
  "projects/repos/drei/src/core/ContactShadows.tsx",
  "projects/repos/drei/src/core/AccumulativeShadows.tsx",
  "projects/repos/drei/src/core/Lightformer.tsx",
  "projects/repos/drei/src/core/Sky.tsx",
  "projects/repos/drei/src/core/OrbitControls.tsx",
  "projects/repos/drei/src/core/CameraControls.tsx",
  "projects/repos/drei/src/core/PerspectiveCamera.tsx",
  "projects/repos/drei/src/core/OrthographicCamera.tsx",
  "projects/repos/drei/src/core/Bounds.tsx",
  "projects/repos/drei/src/core/Center.tsx",
  "projects/repos/drei/src/core/Text.tsx",
  "projects/repos/drei/src/core/Text3D.tsx",
  "projects/repos/drei/src/core/Instances.tsx",
  "projects/repos/drei/src/core/Float.tsx",
  "projects/repos/drei/src/core/CameraShake.tsx",
  "projects/repos/drei/src/core/Image.tsx",
  "projects/repos/drei/src/core/Mask.tsx",
  "projects/repos/drei/src/core/RoundedBox.tsx",
  "projects/repos/drei/src/core/useAnimations.tsx",
  "projects/repos/drei/src/core/useAspect.tsx",
  "projects/repos/drei/src/core/PerformanceMonitor.tsx",
  "projects/repos/drei/src/core/Stats.tsx",
  "projects/repos/drei/src/core/shaderMaterial.tsx",
  "projects/repos/drei/src/web/Html.tsx",
  "projects/repos/drei/src/web/ScrollControls.tsx",
  "projects/repos/drei/src/web/useCursor.tsx",
] as const

export const pmndrsCommonPrimitiveCounts = [
  {
    primitive: "useGLTF",
    importSource: "@react-three/drei",
    sourceFiles: 98,
    demos: 88,
    threeEffectModule: "assetPrimitives",
  },
  {
    primitive: "Environment",
    importSource: "@react-three/drei",
    sourceFiles: 71,
    demos: 70,
    threeEffectModule: "stagingPrimitives",
  },
  {
    primitive: "OrbitControls",
    importSource: "@react-three/drei",
    sourceFiles: 61,
    demos: 61,
    threeEffectModule: "controlsPrimitives",
  },
  {
    primitive: "ContactShadows",
    importSource: "@react-three/drei",
    sourceFiles: 24,
    demos: 24,
    threeEffectModule: "stagingPrimitives",
  },
  {
    primitive: "useTexture",
    importSource: "@react-three/drei",
    sourceFiles: 25,
    demos: 23,
    threeEffectModule: "assetPrimitives",
  },
  {
    primitive: "AccumulativeShadows/RandomizedLight",
    importSource: "@react-three/drei",
    sourceFiles: 40,
    demos: 20,
    threeEffectModule: "stagingPrimitives",
  },
  {
    primitive: "ScrollControls/useScroll",
    importSource: "@react-three/drei",
    sourceFiles: 17,
    demos: 18,
    threeEffectModule: "scrollPrimitives",
  },
  {
    primitive: "Text",
    importSource: "@react-three/drei",
    sourceFiles: 19,
    demos: 18,
    threeEffectModule: "geometryPrimitives",
  },
  {
    primitive: "Float",
    importSource: "@react-three/drei",
    sourceFiles: 17,
    demos: 16,
    threeEffectModule: "motionPrimitives",
  },
  {
    primitive: "PerspectiveCamera/OrthographicCamera",
    importSource: "@react-three/drei",
    sourceFiles: 21,
    demos: 23,
    threeEffectModule: "cameraPrimitives",
  },
  {
    primitive: "Html",
    importSource: "@react-three/drei",
    sourceFiles: 13,
    demos: 13,
    threeEffectModule: "htmlOverlayPrimitives",
  },
  {
    primitive: "Bounds/Center",
    importSource: "@react-three/drei",
    sourceFiles: 19,
    demos: 19,
    threeEffectModule: "cameraPrimitives",
  },
  {
    primitive: "Lightformer",
    importSource: "@react-three/drei",
    sourceFiles: 13,
    demos: 13,
    threeEffectModule: "stagingPrimitives",
  },
  {
    primitive: "CameraControls",
    importSource: "@react-three/drei",
    sourceFiles: 12,
    demos: 12,
    threeEffectModule: "controlsPrimitives partial; full camera-controls parity remains out of core",
  },
  {
    primitive: "Sky",
    importSource: "@react-three/drei",
    sourceFiles: 11,
    demos: 11,
    threeEffectModule: "stagingPrimitives",
  },
  {
    primitive: "useAnimations",
    importSource: "@react-three/drei",
    sourceFiles: 11,
    demos: 11,
    threeEffectModule: "animationPrimitives",
  },
  {
    primitive: "useCursor",
    importSource: "@react-three/drei",
    sourceFiles: 11,
    demos: 11,
    threeEffectModule: "interactionPrimitives",
  },
  {
    primitive: "Instances/Instance",
    importSource: "@react-three/drei",
    sourceFiles: 6,
    demos: 6,
    threeEffectModule: "instancePrimitives",
  },
  {
    primitive: "Image",
    importSource: "@react-three/drei",
    sourceFiles: 8,
    demos: 8,
    threeEffectModule: "imagePrimitives",
  },
  {
    primitive: "Mask/useMask",
    importSource: "@react-three/drei",
    sourceFiles: 11,
    demos: 6,
    threeEffectModule: "maskPrimitives",
  },
  {
    primitive: "RoundedBox",
    importSource: "@react-three/drei",
    sourceFiles: 5,
    demos: 5,
    threeEffectModule: "geometryPrimitives",
  },
  {
    primitive: "useAspect",
    importSource: "@react-three/drei",
    sourceFiles: 5,
    demos: 5,
    threeEffectModule: "geometryPrimitives",
  },
  {
    primitive: "Stats/PerformanceMonitor",
    importSource: "@react-three/drei",
    sourceFiles: 9,
    demos: 9,
    threeEffectModule: "performancePrimitives",
  },
  {
    primitive: "CameraShake",
    importSource: "@react-three/drei",
    sourceFiles: 5,
    demos: 5,
    threeEffectModule: "motionPrimitives",
  },
  {
    primitive: "shaderMaterial",
    importSource: "@react-three/drei",
    sourceFiles: 9,
    demos: 9,
    threeEffectModule: "shaderMaterialPrimitives",
  },
] as const
